#!/bin/bash

# This file is part of NVIDIA Power Manager - indicator applet for NVIDIA
# laptops.
# Copyright (C) 2018 Dmitri Lapin
#
# This work is based on the NVIDIA Power Indicator applet by
# André Brait Carneiro Fabotti
#
# NVIDIA Power Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# NVIDIA Power Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NVIDIA Power Manager. If not, see <http://www.gnu.org/licenses/>.


if [[ $1 == "on" ]]
then
    modprobe nvidia_drm nvidia_modeset nvidia_uvm nvidia &>/dev/null
    tee /proc/acpi/bbswitch <<< ON &>/dev/null
else
    rmmod nvidia_drm nvidia_modeset nvidia_uvm nvidia &>/dev/null
    tee /proc/acpi/bbswitch <<< OFF &>/dev/null
fi

