#!/bin/bash

# This file is part of NVIDIA Power Manager - indicator applet for NVIDIA
# laptops.
# Copyright (C) 2018 Dmitri Lapin
#
# This work is based on the NVIDIA Power Indicator applet by
# André Brait Carneiro Fabotti
#
# NVIDIA Power Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# NVIDIA Power Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NVIDIA Power Manager. If not, see <http://www.gnu.org/licenses/>.


rrmmod() {
    out=$(rmmod $@ 2>&1)
    err=$?
    if [ $err -ne 0 ]; then
        if [[ $out = *"is in use by"* ]]; then
            modules=$(sed -e 's/^.*in use by:\s*//g' <<< $out)
            rrmmod $modules
            rrmmod $@
        fi
    fi
}

if [[ $1 == "on" ]]
then
    tee /proc/acpi/bbswitch <<< ON &>/dev/null
    modprobe nvidia &>/dev/null
else
    # try modprobe -r first
    modprobe -r -a nvidia &>/dev/null
    # if nvidia module is still there, try to rmmod it with dependencies
    out=$(lsmod | grep -w nvidia)
    if [ $? -eq 0 ]; then
        rrmmod nvidia
    fi
    tee /proc/acpi/bbswitch <<< OFF &>/dev/null
fi

